function t = get_pred_arrivaltime( ...
    a0,ad,a1,a2,...
    h_init,h1,h2...
)
global VERTICAL_SCALE

t = ...
    a0+ ...
    VERTICAL_SCALE * ( ...
        ad * h_init + ...
        a1 * h1 + ...
        a2 * h2 ...
    );
end

